### ISSUE TITLE
eslint parsing failure

### ISSUE THREAD

**Issue by carocad** [asyncapi/node-codegen#2]
This code generates Linting errors  on my Atom:

```
async function getFileContent (filePath) {
  return new Promise((resolve, reject) => {
    fs.readFile(path.resolve(__dirname, filePath), (err, content) => {
      if (err) return reject(err);
      resolve(content);
    });
  });
}
```

It looks like the error comes from `async function`.

Apparently it is related to EsLint not being configured properly. I added the following lines to the `.eslintrc` according to this thread: https://github.com/eslint/eslint/issues/8366

```
parserOptions:
  ecmaVersion: 2017
```

and it works now. Not sure if that was really the issue but it seems to work now.

**Comment by fmvilas** [comment]
Yes, that was missing. Thanks for noticing!

**Comment by fmvilas** [comment]
Do you mind creating a PR?
